#!/bin/bash

set -e
set -u

echo " == Creating user and database '$POSTGRES_DATABASE' == "
psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER <<-EOSQL
    CREATE USER $POSTGRES_USER WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD';
    CREATE DATABASE $POSTGRES_DATABASE;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DATABASE TO $POSTGRES_USER;



